name: ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
  steps:
    - run: make checkstyle
    - run: ./gradlew lint
    - run: make test